on:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and Test with Maven
        run: mvn clean test -X

      - name: Debug Classpath
        run: |
          mvn dependency:build-classpath -Dmdep.outputFile=cp.txt
          cat cp.txt
